spring:
  application:
    name: mongodb
  data:
    mongodb:
      uri: ${MONGO_CONN_URI:mongodb://appuser:apppassword@localhost:27017/notification}

logging:
  structured:
    format:
      console: logstash
  level:
    org.springframework.data.mongodb: DEBUG